import type { ListTrackedParams, ListDeliveriesParams, ListDeliveryExceptionsParams, ListPodsParams, ListLocationsParams, ListPodParams, ListOrdersParams, ListShipmentsParams, ListContractsParams, ListAuditLogsParams, ListRequestsParams, ListTransportersParams, ListUsersParams } from './types'

/** One place for cache keys so invalidation after a mutation can never drift from the queries. */
export const queryKeys = {
  users: {
    all: ['users'] as const,
    list: (params: ListUsersParams) => ['users', 'list', params] as const,
  },
  roles: {
    all: ['roles'] as const,
    permissions: ['roles', 'permissions'] as const,
  },
  audit: {
    list: (params: ListAuditLogsParams) => ['audit', 'list', params] as const,
  },
  approvals: {
    all: ['approvals'] as const,
    requests: (params: ListRequestsParams) => ['approvals', 'requests', params] as const,
    request: (id: string) => ['approvals', 'request', id] as const,
    policies: ['approvals', 'policies'] as const,
    stepPermissions: ['approvals', 'policies', 'permissions'] as const,
    delegations: ['approvals', 'delegations'] as const,
  },
  transporters: {
    all: ['transporters'] as const,
    list: (params: ListTransportersParams) => ['transporters', 'list', params] as const,
    detail: (id: string) => ['transporters', 'detail', id] as const,
    vehicles: (id: string, page: number, search?: string) => ['transporters', id, 'vehicles', page, search] as const,
    drivers: (id: string, page: number, search?: string) => ['transporters', id, 'drivers', page, search] as const,
    documents: (id: string) => ['transporters', id, 'documents'] as const,
    vehicleTypes: ['transporters', 'vehicle-types'] as const,
    lookup: (search?: string) => ['transporters', 'lookup', search] as const,
    compliance: (withinDays: number, page: number) => ['transporters', 'compliance', withinDays, page] as const,
  },
  performance: {
    detail: (id: string, from: string, to: string) => ['performance', id, from, to] as const,
    scorecards: (id: string) => ['performance', id, 'scorecards'] as const,
    benchmark: (id: string, from: string, to: string) => ['performance', id, 'benchmark', from, to] as const,
    executions: (id: string) => ['performance', id, 'executions'] as const,
    lanes: (id: string) => ['performance', id, 'lanes'] as const,
    capabilities: (id: string) => ['performance', id, 'capabilities'] as const,
    capabilityCatalog: ['performance', 'capability-catalog'] as const,
    rules: (id: string) => ['performance', id, 'rules'] as const,
    contacts: (id: string) => ['performance', id, 'contacts'] as const,
    branches: (id: string) => ['performance', id, 'branches'] as const,
    claims: (id: string, from: string, to: string) => ['performance', id, 'claims', from, to] as const,
    costs: (id: string, from: string, to: string) => ['performance', id, 'costs', from, to] as const,
    capacity: (id: string, from: string, to: string) => ['performance', id, 'capacity', from, to] as const,
    placements: (params: object) => ['performance', 'placements', params] as const,
    alerts: (params: object) => ['performance', 'alerts', params] as const,
    rankings: (params: object) => ['performance', 'rankings', params] as const,
    settings: ['performance', 'settings'] as const,
    all: ['performance'] as const,
  },
  contracts: {
    all: ['contracts'] as const,
    list: (params: ListContractsParams) => ['contracts', 'list', params] as const,
    detail: (id: string) => ['contracts', 'detail', id] as const,
    rates: (id: string) => ['contracts', id, 'rates'] as const,
    documents: (id: string) => ['contracts', id, 'documents'] as const,
    expiring: (days: number) => ['contracts', 'expiring', days] as const,
    zones: ['contracts', 'zones'] as const,
    vehicleTypes: ['contracts', 'vehicle-types'] as const,
    diesel: ['contracts', 'diesel'] as const,
  },
  freight: {
    all: ['freight'] as const,
    rates: (params: object) => ['freight', 'rates', params] as const,
    rate: (id: string) => ['freight', 'rate', id] as const,
    rateHistory: (id: string) => ['freight', 'rate', id, 'history'] as const,
    ratings: (params: object) => ['freight', 'ratings', params] as const,
    rating: (id: string) => ['freight', 'rating', id] as const,
    dph: (params: object) => ['freight', 'dph', params] as const,
    contractDph: (id: string) => ['freight', 'contract', id, 'dph'] as const,
    priceIndex: (region?: string) => ['freight', 'price-index', region] as const,
    accessorials: ['freight', 'accessorials'] as const,
    contractCharges: (id: string) => ['freight', 'contract', id, 'charges'] as const,
    capacity: (id: string) => ['freight', 'contract', id, 'capacity'] as const,
    sla: (id: string) => ['freight', 'contract', id, 'sla'] as const,
    imports: ['freight', 'imports'] as const,
    import: (id: string) => ['freight', 'import', id] as const,
    dashboard: ['freight', 'dashboard'] as const,
    expiry: ['freight', 'expiry'] as const,
    coverage: ['freight', 'coverage'] as const,
    validation: ['freight', 'validation'] as const,
    usage: ['freight', 'usage'] as const,
    impact: (id: string) => ['freight', 'impact', id] as const,
    versions: (number: string) => ['freight', 'versions', number] as const,
  },
  orders: {
    all: ['orders'] as const,
    list: (params: ListOrdersParams) => ['orders', 'list', params] as const,
  },
  locations: {
    all: ['locations'] as const,
    list: (params: ListLocationsParams) => ['locations', 'list', params] as const,
    active: ['locations', 'active'] as const,
  },
  pod: {
    all: ['pod'] as const,
    queue: (params: ListPodParams) => ['pod', 'queue', params] as const,
    ageing: ['pod', 'ageing'] as const,
    documents: (shipmentId: string, orderId: string) => ['pod', 'documents', shipmentId, orderId] as const,
  },
  milkRuns: {
    all: ['milk-runs'] as const,
    list: (page: number) => ['milk-runs', 'list', page] as const,
  },
  planning: {
    all: ['planning'] as const,
    runs: (page: number) => ['planning', 'runs', page] as const,
    run: (id: string) => ['planning', 'run', id] as const,
    versions: (id: string) => ['planning', 'versions', id] as const,
    openOrders: ['planning', 'open-orders'] as const,
    compatibility: ['planning', 'compatibility-rules'] as const,
    dashboard: (from?: string, to?: string) => ['planning', 'dashboard', from, to] as const,
  },
  deliveries: {
    all: ['deliveries'] as const,
    list: (params: ListDeliveriesParams) => ['deliveries', 'list', params] as const,
    detail: (id: string) => ['deliveries', 'detail', id] as const,
    pods: (params: ListPodsParams) => ['deliveries', 'pods', params] as const,
    reviewQueue: (params: ListPodsParams) => ['deliveries', 'review-queue', params] as const,
    pod: (id: string) => ['deliveries', 'pod', id] as const,
    review: (id: string) => ['deliveries', 'review', id] as const,
    exceptions: (params: ListDeliveryExceptionsParams) => ['deliveries', 'exceptions', params] as const,
    exception: (id: string) => ['deliveries', 'exception', id] as const,
    settings: ['deliveries', 'settings'] as const,
    dashboard: (params: object) => ['deliveries', 'dashboard', params] as const,
    ageing: (transporterId?: string) => ['deliveries', 'ageing', transporterId] as const,
    ageingItems: (params: object) => ['deliveries', 'ageing-items', params] as const,
    compliance: (params: object) => ['deliveries', 'compliance', params] as const,
    notifications: (params: object) => ['deliveries', 'notifications', params] as const,
    billing: (id: string) => ['deliveries', 'billing', id] as const,
    proofPerformance: (id: string) => ['deliveries', 'proof-performance', id] as const,
    mobile: ['deliveries', 'mobile'] as const,
  },
  masterData: {
    types: ['master-data', 'types'] as const,
    capabilityTypes: ['master-data', 'capability-types'] as const,
    documentRules: ['master-data', 'document-rules'] as const,
  },
  shipments: {
    all: ['shipments'] as const,
    list: (params: ListShipmentsParams) => ['shipments', 'list', params] as const,
    detail: (id: string) => ['shipments', 'detail', id] as const,
    quotes: (id: string) => ['shipments', id, 'quotes'] as const,
    fleet: (id: string) => ['shipments', id, 'fleet'] as const,
    tenders: (id: string) => ['shipments', id, 'tenders'] as const,
    vehicleTypes: ['shipments', 'vehicle-types'] as const,
    suggestions: ['shipments', 'suggestions'] as const,
    utilization: ['shipments', 'utilization'] as const,
  },
  tracking: {
    all: ['tracking'] as const,
    summary: (transporterId?: string) => ['tracking', 'summary', transporterId] as const,
    list: (params: ListTrackedParams) => ['tracking', 'list', params] as const,
    map: ['tracking', 'map'] as const,
    detail: (id: string) => ['tracking', 'detail', id] as const,
    part: (id: string, part: string, extra?: unknown) => ['tracking', 'detail', id, part, extra] as const,
    vehicles: (params: object) => ['tracking', 'vehicles', params] as const,
    alerts: (params: object) => ['tracking', 'alerts', params] as const,
    exceptions: (params: object) => ['tracking', 'exceptions', params] as const,
    exception: (id: string) => ['tracking', 'exception', id] as const,
    geofences: ['tracking', 'geofences'] as const,
    compliance: (params: object) => ['tracking', 'compliance', params] as const,
    replay: (id: string, params: object) => ['tracking', 'replay', id, params] as const,
    settings: ['tracking', 'settings'] as const,
    links: (id: string) => ['tracking', 'links', id] as const,
    trips: ['tracking', 'trips'] as const,
    customer: (token: string) => ['tracking', 'customer', token] as const,
  },
}
