// <auto-generated />
using System;
using LogiVue.Tms.TransporterManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogiVue.Tms.TransporterManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TransporterDbContext))]
    [Migration("20261004090947_TenderingAndVendorPortal")]
    partial class TenderingAndVendorPortal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Alerts.TransporterAlert", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("LoadReference")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long>("TransporterId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DueAt");

                    b.HasIndex("Severity");

                    b.HasIndex("Status");

                    b.HasIndex("TransporterId");

                    b.ToTable("tm_transporter_alerts", (string)null);
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Alerts.TransporterException", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionTaken")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("LoadReference")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Owner")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RootCause")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long>("TransporterId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Severity");

                    b.HasIndex("Status");

                    b.HasIndex("TransporterId");

                    b.ToTable("tm_transporter_exceptions", (string)null);
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Audit.TransporterAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("NewValueJson")
                        .HasColumnType("json");

                    b.Property<string>("OldValueJson")
                        .HasColumnType("json");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("PerformedAt");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("tm_transporter_audit_logs", (string)null);
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Configuration.CapabilityType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("tm_capability_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "FTL",
                            IsActive = true,
                            Name = "FTL"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "PTL",
                            IsActive = true,
                            Name = "PTL"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "HAZARDOUS",
                            IsActive = true,
                            Name = "Hazardous"
                        },
                        new
                        {
                            Id = 4L,
                            Code = "TEMP_CONTROLLED",
                            IsActive = true,
                            Name = "Temperature Controlled"
                        },
                        new
                        {
                            Id = 5L,
                            Code = "FRAGILE",
                            IsActive = true,
                            Name = "Fragile"
                        },
                        new
                        {
                            Id = 6L,
                            Code = "HEAVY_CARGO",
                            IsActive = true,
                            Name = "Heavy Cargo"
                        },
                        new
                        {
                            Id = 7L,
                            Code = "HIGH_VALUE",
                            IsActive = true,
                            Name = "High Value"
                        },
                        new
                        {
                            Id = 8L,
                            Code = "REVERSE_LOGISTICS",
                            IsActive = true,
                            Name = "Reverse Logistics"
                        },
                        new
                        {
                            Id = 9L,
                            Code = "MILK_RUN",
                            IsActive = true,
                            Name = "Milk Run"
                        },
                        new
                        {
                            Id = 10L,
                            Code = "EXPRESS",
                            IsActive = true,
                            Name = "Express"
                        },
                        new
                        {
                            Id = 11L,
                            Code = "DEDICATED",
                            IsActive = true,
                            Name = "Dedicated"
                        });
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Configuration.ConfigurationSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("tm_configuration_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Key = "tm.scorecard.weights.default",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed",
                            ValueJson = "{\"OnTimePickup\":10,\"OnTimeDelivery\":25,\"PlacementCompliance\":15,\"TenderAcceptance\":10,\"PodCompliance\":5,\"ClaimsRate\":10,\"CostPerformance\":15,\"Availability\":10}",
                            Version = 1
                        },
                        new
                        {
                            Id = 2L,
                            Key = "tm.scorecard.minimumSampleSize",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed",
                            ValueJson = "20",
                            Version = 1
                        },
                        new
                        {
                            Id = 3L,
                            Key = "tm.tender.responseSlaMinutes",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed",
                            ValueJson = "30",
                            Version = 1
                        },
                        new
                        {
                            Id = 4L,
                            Key = "tm.placement.alertMinutesBefore",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed",
                            ValueJson = "30",
                            Version = 1
                        },
                        new
                        {
                            Id = 5L,
                            Key = "tm.pod.submissionSlaHours",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed",
                            ValueJson = "24",
                            Version = 1
                        },
                        new
                        {
                            Id = 6L,
                            Key = "tm.compliance.renewalReminderDays",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed",
                            ValueJson = "30",
                            Version = 1
                        },
                        new
                        {
                            Id = 7L,
                            Key = "tm.performance.thresholds",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed",
                            ValueJson = "{\"OnTimeDelivery\":{\"Excellent\":95,\"Acceptable\":90},\"PlacementCompliance\":{\"Excellent\":95,\"Acceptable\":90},\"PodCompliance\":{\"Excellent\":98,\"Acceptable\":95}}",
                            Version = 1
                        },
                        new
                        {
                            Id = 8L,
                            Key = "tm.alerts.enabled",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed",
                            ValueJson = "true",
                            Version = 1
                        },
                        new
                        {
                            Id = 9L,
                            Key = "tm.alerts.delayEscalationMinutes",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed",
                            ValueJson = "{\"CoordinatorMinutes\":0,\"ManagerAfterMinutes\":60,\"HeadAfterMinutes\":120}",
                            Version = 1
                        },
                        new
                        {
                            Id = 10L,
                            Key = "tm.recommendation.weights",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed",
                            ValueJson = "{\"Rate\":30,\"OnTimePickup\":20,\"OnTimeDelivery\":15,\"PlacementCompliance\":10,\"PodCompliance\":5,\"TenderAcceptance\":5,\"ClaimsRate\":5,\"Availability\":10}",
                            Version = 1
                        },
                        new
                        {
                            Id = 11L,
                            Key = "tm.recommendation.scoring",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed",
                            ValueJson = "{\"ClaimsZeroAtPct\":5,\"AvailabilityPerVehicle\":40,\"PreferredBonus\":5,\"InsufficientDataScore\":60}",
                            Version = 1
                        },
                        new
                        {
                            Id = 12L,
                            Key = "tm.performance.windowDays",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed",
                            ValueJson = "90",
                            Version = 1
                        },
                        new
                        {
                            Id = 13L,
                            Key = "tm.eligibility.restrictions",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed",
                            ValueJson = "{\"Enabled\":false,\"MinOtdPct\":90,\"MaxClaimsRatePct\":3}",
                            Version = 1
                        },
                        new
                        {
                            Id = 14L,
                            Key = "tm.tender.rejectionReasons",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed",
                            ValueJson = "[\"VEHICLE_UNAVAILABLE\",\"LANE_UNAVAILABLE\",\"RATE_ISSUE\",\"PICKUP_TIME_ISSUE\",\"CAPACITY_UNAVAILABLE\",\"DESTINATION_ISSUE\",\"OTHER\"]",
                            Version = 1
                        },
                        new
                        {
                            Id = 15L,
                            Key = "tm.tender.allowCounterOffer",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed",
                            ValueJson = "false",
                            Version = 1
                        });
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Configuration.DocumentType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("BlockAllocationWhenExpired")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<bool>("ExpiryRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDriverLevel")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTransporterLevel")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsVehicleLevel")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("RenewalReminderDays")
                        .HasColumnType("int");

                    b.Property<bool>("VerificationRequired")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("tm_document_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BlockAllocationWhenExpired = false,
                            Code = "GST_CERT",
                            ExpiryRequired = false,
                            IsActive = true,
                            IsDriverLevel = false,
                            IsMandatory = true,
                            IsTransporterLevel = true,
                            IsVehicleLevel = false,
                            Name = "GST Certificate",
                            RenewalReminderDays = 30,
                            VerificationRequired = true
                        },
                        new
                        {
                            Id = 2L,
                            BlockAllocationWhenExpired = false,
                            Code = "PAN",
                            ExpiryRequired = false,
                            IsActive = true,
                            IsDriverLevel = false,
                            IsMandatory = true,
                            IsTransporterLevel = true,
                            IsVehicleLevel = false,
                            Name = "PAN",
                            VerificationRequired = true
                        },
                        new
                        {
                            Id = 3L,
                            BlockAllocationWhenExpired = false,
                            Code = "COMPANY_REG",
                            ExpiryRequired = false,
                            IsActive = true,
                            IsDriverLevel = false,
                            IsMandatory = true,
                            IsTransporterLevel = true,
                            IsVehicleLevel = false,
                            Name = "Company Registration",
                            VerificationRequired = true
                        },
                        new
                        {
                            Id = 4L,
                            BlockAllocationWhenExpired = true,
                            Code = "INSURANCE",
                            ExpiryRequired = true,
                            IsActive = true,
                            IsDriverLevel = false,
                            IsMandatory = true,
                            IsTransporterLevel = false,
                            IsVehicleLevel = true,
                            Name = "Insurance",
                            RenewalReminderDays = 30,
                            VerificationRequired = true
                        },
                        new
                        {
                            Id = 5L,
                            BlockAllocationWhenExpired = true,
                            Code = "PERMIT",
                            ExpiryRequired = true,
                            IsActive = true,
                            IsDriverLevel = false,
                            IsMandatory = false,
                            IsTransporterLevel = true,
                            IsVehicleLevel = true,
                            Name = "Permit",
                            RenewalReminderDays = 30,
                            VerificationRequired = true
                        },
                        new
                        {
                            Id = 6L,
                            BlockAllocationWhenExpired = true,
                            Code = "FITNESS",
                            ExpiryRequired = true,
                            IsActive = true,
                            IsDriverLevel = false,
                            IsMandatory = false,
                            IsTransporterLevel = true,
                            IsVehicleLevel = true,
                            Name = "Fitness Certificate",
                            RenewalReminderDays = 30,
                            VerificationRequired = true
                        },
                        new
                        {
                            Id = 7L,
                            BlockAllocationWhenExpired = false,
                            Code = "PUC",
                            ExpiryRequired = true,
                            IsActive = true,
                            IsDriverLevel = false,
                            IsMandatory = false,
                            IsTransporterLevel = true,
                            IsVehicleLevel = true,
                            Name = "PUC",
                            RenewalReminderDays = 15,
                            VerificationRequired = true
                        },
                        new
                        {
                            Id = 8L,
                            BlockAllocationWhenExpired = false,
                            Code = "VEHICLE_RC",
                            ExpiryRequired = false,
                            IsActive = true,
                            IsDriverLevel = false,
                            IsMandatory = false,
                            IsTransporterLevel = false,
                            IsVehicleLevel = true,
                            Name = "Vehicle RC",
                            VerificationRequired = true
                        },
                        new
                        {
                            Id = 9L,
                            BlockAllocationWhenExpired = true,
                            Code = "DRIVER_LICENCE",
                            ExpiryRequired = true,
                            IsActive = true,
                            IsDriverLevel = true,
                            IsMandatory = false,
                            IsTransporterLevel = false,
                            IsVehicleLevel = false,
                            Name = "Driver Licence",
                            RenewalReminderDays = 30,
                            VerificationRequired = true
                        },
                        new
                        {
                            Id = 10L,
                            BlockAllocationWhenExpired = false,
                            Code = "OTHER",
                            ExpiryRequired = false,
                            IsActive = true,
                            IsDriverLevel = false,
                            IsMandatory = false,
                            IsTransporterLevel = true,
                            IsVehicleLevel = false,
                            Name = "Other",
                            VerificationRequired = true
                        });
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Configuration.OnboardingStep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RequiredRole")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Sequence")
                        .IsUnique();

                    b.HasIndex("Status")
                        .IsUnique();

                    b.ToTable("tm_onboarding_steps", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsActive = true,
                            Name = "Document Verification",
                            RequiredRole = "Compliance User",
                            Sequence = 1,
                            Status = "DocumentVerification"
                        },
                        new
                        {
                            Id = 2L,
                            IsActive = true,
                            Name = "Operations Review",
                            RequiredRole = "Operations User",
                            Sequence = 2,
                            Status = "OperationsReview"
                        },
                        new
                        {
                            Id = 3L,
                            IsActive = true,
                            Name = "Commercial Review",
                            RequiredRole = "Transport Manager",
                            Sequence = 3,
                            Status = "CommercialReview"
                        },
                        new
                        {
                            Id = 4L,
                            IsActive = true,
                            Name = "Finance Review",
                            RequiredRole = "Finance User",
                            Sequence = 4,
                            Status = "FinanceReview"
                        });
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Configuration.TransporterType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("tm_transporter_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "FTL",
                            IsActive = true,
                            Name = "Full Truck Load"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "PTL",
                            IsActive = true,
                            Name = "Part Truck Load"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "EXPRESS",
                            IsActive = true,
                            Name = "Express"
                        },
                        new
                        {
                            Id = 4L,
                            Code = "DEDICATED",
                            IsActive = true,
                            Name = "Dedicated"
                        },
                        new
                        {
                            Id = 5L,
                            Code = "LAST_MILE",
                            IsActive = true,
                            Name = "Last Mile"
                        },
                        new
                        {
                            Id = 6L,
                            Code = "MILK_RUN",
                            IsActive = true,
                            Name = "Milk Run"
                        },
                        new
                        {
                            Id = 7L,
                            Code = "FLEET_OWNER",
                            IsActive = true,
                            Name = "Fleet Owner"
                        },
                        new
                        {
                            Id = 8L,
                            Code = "BROKER",
                            IsActive = true,
                            Name = "Broker"
                        },
                        new
                        {
                            Id = 9L,
                            Code = "3PL",
                            IsActive = true,
                            Name = "Third-Party Logistics"
                        });
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Performance.PerformanceKpi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CalculationVersion")
                        .HasColumnType("int");

                    b.Property<decimal>("Denominator")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("KpiType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<decimal?>("KpiValue")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<long?>("LaneReference")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Numerator")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<long>("TransporterId")
                        .HasColumnType("bigint");

                    b.Property<long?>("VehicleTypeReference")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LaneReference");

                    b.HasIndex("TransporterId");

                    b.HasIndex("TransporterId", "KpiType", "PeriodStart", "PeriodEnd");

                    b.ToTable("tm_transporter_performance_kpis", (string)null);
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Performance.ScorecardDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("BenchmarkValue")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("KpiType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<decimal?>("KpiValue")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<long>("ScorecardId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Trend")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("WeightedScore")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.HasKey("Id");

                    b.HasIndex("ScorecardId");

                    b.ToTable("tm_transporter_scorecard_details", (string)null);
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Performance.TransporterRanking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("LaneReference")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<long>("TransporterId")
                        .HasColumnType("bigint");

                    b.Property<long?>("VehicleTypeReference")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TransporterId", "PeriodStart", "PeriodEnd");

                    b.HasIndex("LaneReference", "PeriodStart", "PeriodEnd", "Rank");

                    b.ToTable("tm_transporter_rankings", (string)null);
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Performance.TransporterScorecard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CalculationVersion")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("OverallScore")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<int?>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("ScorecardProfile")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long>("TransporterId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TransporterId", "PeriodStart", "PeriodEnd");

                    b.ToTable("tm_transporter_scorecards", (string)null);
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Placement.VehiclePlacementEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("EventAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<long>("PlacementRequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<long?>("VehicleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PlacementRequestId");

                    b.ToTable("tm_vehicle_placement_events", (string)null);
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Placement.VehiclePlacementRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExceptionReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("LoadReference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LoadingStartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("PlacedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ReportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("RequiredPlacementAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<long>("TransporterId")
                        .HasColumnType("bigint");

                    b.Property<long?>("VehicleTypeReference")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LoadReference");

                    b.HasIndex("Status");

                    b.HasIndex("TransporterId");

                    b.ToTable("tm_vehicle_placement_requests", (string)null);
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Planning.TransporterPlanningFeedback", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AvailabilityScore")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal?>("ClaimsRatePct")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal?>("CostPerformanceScore")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<long?>("LaneReference")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("OtdPct")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal?>("OtpPct")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal?>("OverallScore")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal?>("PlacementCompliancePct")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal?>("PodCompliancePct")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<bool>("PreferredFlag")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("RecommendationScore")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<bool>("RestrictedFlag")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("TenderAcceptancePct")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<long>("TransporterId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TransporterId", "LaneReference")
                        .IsUnique();

                    b.ToTable("tm_transporter_planning_feedback", (string)null);
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Planning.TransporterPlanningRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("LaneReference")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<long>("TransporterId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TransporterId", "RuleType");

                    b.ToTable("tm_transporter_planning_rules", (string)null);
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Tendering.Tender", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("DeliveryDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("DestinationLocationReference")
                        .HasColumnType("bigint");

                    b.Property<string>("LoadReference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<decimal?>("OfferedRate")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<long>("OriginLocationReference")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PickupDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ResponseDeadline")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenderNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("TenderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long>("TransporterId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("VehicleTypeReference")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("VolumeM3")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ResponseDeadline");

                    b.HasIndex("Status");

                    b.HasIndex("TenderNumber");

                    b.HasIndex("TransporterId");

                    b.ToTable("tm_tenders", (string)null);
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Tendering.TenderEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("EventAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<long>("TenderId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenderId");

                    b.ToTable("tm_tender_events", (string)null);
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Tendering.TenderResponse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("DriverMobile")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("DriverReference")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<DateTime?>("EtaAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExpectedPlacementAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("QuotedRate")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Reason")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("ResponseAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("TenderId")
                        .HasColumnType("bigint");

                    b.Property<long>("TransporterId")
                        .HasColumnType("bigint");

                    b.Property<long?>("VehicleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenderId");

                    b.ToTable("tm_tender_responses", (string)null);
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Transporters.Transporter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CompanyType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Gstin")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Pan")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PrimaryContactEmail")
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)");

                    b.Property<string>("PrimaryContactName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PrimaryContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("TradeName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TransporterCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<long?>("TransporterTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Gstin");

                    b.HasIndex("Status");

                    b.HasIndex("TransporterCode")
                        .IsUnique();

                    b.HasIndex("TransporterTypeId");

                    b.ToTable("tm_transporters", (string)null);
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Transporters.TransporterBranch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<long>("TransporterId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TransporterId", "BranchCode")
                        .IsUnique();

                    b.ToTable("tm_transporter_branches", (string)null);
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Transporters.TransporterCapability", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CapabilityTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long>("TransporterId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CapabilityTypeId");

                    b.HasIndex("TransporterId", "CapabilityTypeId");

                    b.ToTable("tm_transporter_capabilities", (string)null);
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Transporters.TransporterContact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<long>("TransporterId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TransporterId");

                    b.ToTable("tm_transporter_contacts", (string)null);
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Transporters.TransporterDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<long>("DocumentTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("FileReference")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<long>("TransporterId")
                        .HasColumnType("bigint");

                    b.Property<long?>("VehicleId")
                        .HasColumnType("bigint");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VerifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("ExpiryDate");

                    b.HasIndex("TransporterId");

                    b.HasIndex("VerificationStatus");

                    b.ToTable("tm_transporter_documents", (string)null);
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Transporters.TransporterLane", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DestinationLocationReference")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("OriginLocationReference")
                        .HasColumnType("bigint");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("TransitSlaMinutes")
                        .HasColumnType("int");

                    b.Property<long>("TransporterId")
                        .HasColumnType("bigint");

                    b.Property<long?>("VehicleTypeReference")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TransporterId");

                    b.HasIndex("OriginLocationReference", "DestinationLocationReference", "ServiceType");

                    b.ToTable("tm_transporter_lanes", (string)null);
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Transporters.TransporterRate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<long>("DestinationLocationReference")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("FuelSurcharge")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("MinimumCharge")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<long>("OriginLocationReference")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("OtherCharges")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("RateType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("RateValue")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("TollAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<long>("TransporterId")
                        .HasColumnType("bigint");

                    b.Property<long?>("VehicleTypeReference")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TransporterId");

                    b.HasIndex("OriginLocationReference", "DestinationLocationReference", "ServiceType");

                    b.ToTable("tm_transporter_rates", (string)null);
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Transporters.TransporterUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long>("TransporterId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TransporterId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("tm_transporter_users", (string)null);
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Transporters.TransporterVehicle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AvailabilityStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long?>("CurrentLocationReference")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("HeightM")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("LengthM")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("OwnershipType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("PayloadCapacityKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long>("TransporterId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("UsableVolumeM3")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<long>("VehicleTypeReference")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("WidthM")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("AvailabilityStatus");

                    b.HasIndex("VehicleTypeReference");

                    b.HasIndex("TransporterId", "RegistrationNumber")
                        .IsUnique();

                    b.ToTable("tm_transporter_vehicles", (string)null);
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Workflow.TransporterApprovalAction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("ActionAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<long>("TransporterId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TransporterId", "ActionAt");

                    b.ToTable("tm_transporter_approval_actions", (string)null);
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Alerts.TransporterAlert", b =>
                {
                    b.HasOne("LogiVue.Tms.TransporterManagement.Domain.Transporters.Transporter", null)
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Alerts.TransporterException", b =>
                {
                    b.HasOne("LogiVue.Tms.TransporterManagement.Domain.Transporters.Transporter", null)
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Performance.PerformanceKpi", b =>
                {
                    b.HasOne("LogiVue.Tms.TransporterManagement.Domain.Transporters.Transporter", null)
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Performance.ScorecardDetail", b =>
                {
                    b.HasOne("LogiVue.Tms.TransporterManagement.Domain.Performance.TransporterScorecard", null)
                        .WithMany()
                        .HasForeignKey("ScorecardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Performance.TransporterRanking", b =>
                {
                    b.HasOne("LogiVue.Tms.TransporterManagement.Domain.Transporters.Transporter", null)
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Performance.TransporterScorecard", b =>
                {
                    b.HasOne("LogiVue.Tms.TransporterManagement.Domain.Transporters.Transporter", null)
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Placement.VehiclePlacementEvent", b =>
                {
                    b.HasOne("LogiVue.Tms.TransporterManagement.Domain.Placement.VehiclePlacementRequest", null)
                        .WithMany()
                        .HasForeignKey("PlacementRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Placement.VehiclePlacementRequest", b =>
                {
                    b.HasOne("LogiVue.Tms.TransporterManagement.Domain.Transporters.Transporter", null)
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Planning.TransporterPlanningFeedback", b =>
                {
                    b.HasOne("LogiVue.Tms.TransporterManagement.Domain.Transporters.Transporter", null)
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Planning.TransporterPlanningRule", b =>
                {
                    b.HasOne("LogiVue.Tms.TransporterManagement.Domain.Transporters.Transporter", null)
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Tendering.Tender", b =>
                {
                    b.HasOne("LogiVue.Tms.TransporterManagement.Domain.Transporters.Transporter", null)
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Tendering.TenderEvent", b =>
                {
                    b.HasOne("LogiVue.Tms.TransporterManagement.Domain.Tendering.Tender", null)
                        .WithMany()
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Tendering.TenderResponse", b =>
                {
                    b.HasOne("LogiVue.Tms.TransporterManagement.Domain.Tendering.Tender", null)
                        .WithMany()
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Transporters.Transporter", b =>
                {
                    b.HasOne("LogiVue.Tms.TransporterManagement.Domain.Configuration.TransporterType", null)
                        .WithMany()
                        .HasForeignKey("TransporterTypeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Transporters.TransporterBranch", b =>
                {
                    b.HasOne("LogiVue.Tms.TransporterManagement.Domain.Transporters.Transporter", null)
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Transporters.TransporterCapability", b =>
                {
                    b.HasOne("LogiVue.Tms.TransporterManagement.Domain.Configuration.CapabilityType", null)
                        .WithMany()
                        .HasForeignKey("CapabilityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogiVue.Tms.TransporterManagement.Domain.Transporters.Transporter", null)
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Transporters.TransporterContact", b =>
                {
                    b.HasOne("LogiVue.Tms.TransporterManagement.Domain.Transporters.Transporter", null)
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Transporters.TransporterDocument", b =>
                {
                    b.HasOne("LogiVue.Tms.TransporterManagement.Domain.Configuration.DocumentType", null)
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogiVue.Tms.TransporterManagement.Domain.Transporters.Transporter", null)
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Transporters.TransporterLane", b =>
                {
                    b.HasOne("LogiVue.Tms.TransporterManagement.Domain.Transporters.Transporter", null)
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Transporters.TransporterRate", b =>
                {
                    b.HasOne("LogiVue.Tms.TransporterManagement.Domain.Transporters.Transporter", null)
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Transporters.TransporterUser", b =>
                {
                    b.HasOne("LogiVue.Tms.TransporterManagement.Domain.Transporters.Transporter", null)
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Transporters.TransporterVehicle", b =>
                {
                    b.HasOne("LogiVue.Tms.TransporterManagement.Domain.Transporters.Transporter", null)
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LogiVue.Tms.TransporterManagement.Domain.Workflow.TransporterApprovalAction", b =>
                {
                    b.HasOne("LogiVue.Tms.TransporterManagement.Domain.Transporters.Transporter", null)
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
