// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tms.Modules.Contracts.Infrastructure.Persistence;

#nullable disable

namespace Tms.Modules.Contracts.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ContractsDbContext))]
    [Migration("20261007052456_FreightRatingEngine")]
    partial class FreightRatingEngine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("contracts")
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Tms.Modules.Contracts.Domain.AccessorialType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Calc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("calc");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("unit");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_accessorial_types");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_accessorial_types_tenant_id_code");

                    b.ToTable("accessorial_types", "contracts");
                });

            modelBuilder.Entity("Tms.Modules.Contracts.Domain.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("activated_at");

                    b.Property<Guid?>("ApprovalRequestId")
                        .HasColumnType("char(36)")
                        .HasColumnName("approval_request_id");

                    b.Property<bool>("AutoRenewal")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("auto_renewal");

                    b.Property<string>("BusinessUnit")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("business_unit");

                    b.Property<string>("CalculationVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("1.0")
                        .HasColumnName("calculation_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasDefaultValue("INR")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<decimal?>("EstimatedAnnualSpend")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("estimated_annual_spend");

                    b.Property<string>("Fuel")
                        .HasColumnType("json")
                        .HasColumnName("fuel");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("number");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("owner_user_id");

                    b.Property<int>("PaymentTermsDays")
                        .HasColumnType("int")
                        .HasColumnName("payment_terms_days");

                    b.Property<string>("PrimaryContact")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("primary_contact");

                    b.Property<int>("RateCount")
                        .HasColumnType("int")
                        .HasColumnName("rate_count");

                    b.Property<int>("RatesRevision")
                        .HasColumnType("int")
                        .HasColumnName("rates_revision");

                    b.Property<int>("RenewalNoticeDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(60)
                        .HasColumnName("renewal_notice_days");

                    b.Property<int>("Revision")
                        .HasColumnType("int")
                        .HasColumnName("revision");

                    b.Property<string>("RevisionKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasDefaultValue("Original")
                        .HasColumnName("revision_kind");

                    b.Property<Guid?>("RevisionOfId")
                        .HasColumnType("char(36)")
                        .HasColumnName("revision_of_id");

                    b.Property<string>("Services")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("json")
                        .HasColumnName("services")
                        .HasDefaultValueSql("(JSON_ARRAY())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Suspensions")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("json")
                        .HasColumnName("suspensions")
                        .HasDefaultValueSql("(JSON_ARRAY())");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TerminationReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("termination_reason");

                    b.Property<string>("Terms")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("terms");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("TransporterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("transporter_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("type");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_contracts");

                    b.HasIndex("TenantId", "Number", "Revision")
                        .IsUnique()
                        .HasDatabaseName("ix_contracts_tenant_id_number_revision");

                    b.HasIndex("TenantId", "Status", "EffectiveTo")
                        .HasDatabaseName("ix_contracts_tenant_id_status_effective_to");

                    b.HasIndex("TenantId", "TransporterId", "Status")
                        .HasDatabaseName("ix_contracts_tenant_id_transporter_id_status");

                    b.ToTable("contracts", "contracts");
                });

            modelBuilder.Entity("Tms.Modules.Contracts.Domain.ContractAccessorial", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("char(36)")
                        .HasColumnName("contract_id");

                    b.Property<string>("Spec")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("spec");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_contract_accessorials");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_contract_accessorials_contract_id");

                    b.ToTable("contract_accessorials", "contracts");
                });

            modelBuilder.Entity("Tms.Modules.Contracts.Domain.ContractCapacity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("char(36)")
                        .HasColumnName("contract_id");

                    b.Property<string>("Spec")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("spec");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_contract_capacity");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_contract_capacity_contract_id");

                    b.ToTable("contract_capacity", "contracts");
                });

            modelBuilder.Entity("Tms.Modules.Contracts.Domain.ContractDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("content_type");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("char(36)")
                        .HasColumnName("contract_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<int>("DocumentVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("document_version");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<string>("FileKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("file_key");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("file_name");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Number")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("number");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("verified_at");

                    b.Property<Guid?>("VerifiedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("verified_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasIndex("TenantId", "ContractId")
                        .HasDatabaseName("ix_documents_tenant_id_contract_id");

                    b.HasIndex("TenantId", "ExpiryDate")
                        .HasDatabaseName("ix_documents_tenant_id_expiry_date");

                    b.ToTable("documents", "contracts");
                });

            modelBuilder.Entity("Tms.Modules.Contracts.Domain.ContractSla", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("char(36)")
                        .HasColumnName("contract_id");

                    b.Property<string>("Spec")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("spec");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_contract_sla");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_contract_sla_contract_id");

                    b.ToTable("contract_sla", "contracts");
                });

            modelBuilder.Entity("Tms.Modules.Contracts.Domain.DieselPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("modified_by");

                    b.Property<decimal>("PricePerLitre")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("price_per_litre");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("region");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("source");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_diesel_prices");

                    b.HasIndex("TenantId", "Region", "EffectiveFrom")
                        .IsUnique()
                        .HasDatabaseName("ix_diesel_prices_tenant_id_region_effective_from");

                    b.ToTable("diesel_prices", "contracts");
                });

            modelBuilder.Entity("Tms.Modules.Contracts.Domain.DphPeriodSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<decimal>("AdjustmentPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("adjustment_percent");

                    b.Property<string>("CalculationVersion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("calculation_version");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("char(36)")
                        .HasColumnName("contract_id");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<decimal>("ReferencePrice")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("reference_price");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("rule_code");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("rule_id");

                    b.Property<int>("RuleVersion")
                        .HasColumnType("int")
                        .HasColumnName("rule_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("VariationPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("variation_percent");

                    b.HasKey("Id")
                        .HasName("pk_dph_snapshots");

                    b.HasIndex("RuleId", "PeriodStart")
                        .IsUnique()
                        .HasDatabaseName("ix_dph_snapshots_rule_id_period_start");

                    b.HasIndex("TenantId", "ContractId")
                        .HasDatabaseName("ix_dph_snapshots_tenant_id_contract_id");

                    b.ToTable("dph_snapshots", "contracts");
                });

            modelBuilder.Entity("Tms.Modules.Contracts.Domain.DphRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("char(36)")
                        .HasColumnName("contract_id");

                    b.Property<string>("Spec")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("spec");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_dph_rules");

                    b.HasIndex("ContractId", "Version")
                        .HasDatabaseName("ix_dph_rules_contract_id_version");

                    b.ToTable("dph_rules", "contracts");
                });

            modelBuilder.Entity("Tms.Modules.Contracts.Domain.ExpiryAlert", b =>
                {
                    b.Property<Guid>("ContractId")
                        .HasColumnType("char(36)")
                        .HasColumnName("contract_id");

                    b.Property<int>("DaysBefore")
                        .HasColumnType("int")
                        .HasColumnName("days_before");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("sent_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("ContractId", "DaysBefore")
                        .HasName("pk_expiry_alerts");

                    b.ToTable("expiry_alerts", "contracts");
                });

            modelBuilder.Entity("Tms.Modules.Contracts.Domain.FreightRating", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<decimal>("AccessorialAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("accessorial_amount");

                    b.Property<decimal>("BaseFreight")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("base_freight");

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("calculated_at");

                    b.Property<string>("CalculationVersion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("calculation_version");

                    b.Property<bool>("Committed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("committed");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("char(36)")
                        .HasColumnName("contract_id");

                    b.Property<string>("ContractReference")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("contract_reference");

                    b.Property<int?>("ContractRevision")
                        .HasColumnType("int")
                        .HasColumnName("contract_revision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("currency");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("discount_amount");

                    b.Property<decimal?>("DistanceKm")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("distance_km");

                    b.Property<decimal>("DphAdjustment")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("dph_adjustment");

                    b.Property<string>("DphRuleCode")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("dph_rule_code");

                    b.Property<Guid?>("DphRuleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("dph_rule_id");

                    b.Property<int?>("DphVersion")
                        .HasColumnType("int")
                        .HasColumnName("dph_version");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("error_code");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("input_json");

                    b.Property<string>("Lane")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("lane");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("modified_by");

                    b.Property<DateTimeOffset?>("OverriddenAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("overridden_at");

                    b.Property<Guid?>("OverriddenBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("overridden_by");

                    b.Property<decimal?>("OverrideAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("override_amount");

                    b.Property<string>("OverrideApprovedBy")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("override_approved_by");

                    b.Property<string>("OverrideReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("override_reason");

                    b.Property<bool>("Qualified")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("qualified");

                    b.Property<Guid?>("RateCardId")
                        .HasColumnType("char(36)")
                        .HasColumnName("rate_card_id");

                    b.Property<string>("RateCode")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("rate_code");

                    b.Property<int?>("RateVersion")
                        .HasColumnType("int")
                        .HasColumnName("rate_version");

                    b.Property<string>("ReasonsJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("reasons_json");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("reference");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("service");

                    b.Property<DateOnly>("ShipmentDate")
                        .HasColumnType("date")
                        .HasColumnName("shipment_date");

                    b.Property<string>("ShipmentReference")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("shipment_reference");

                    b.Property<int>("StopCount")
                        .HasColumnType("int")
                        .HasColumnName("stop_count");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalFreight")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("total_freight");

                    b.Property<string>("TraceJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("trace_json");

                    b.Property<Guid?>("TransporterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("transporter_id");

                    b.Property<Guid?>("VehicleTypeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("vehicle_type_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<decimal?>("VolumeCbm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("volume_cbm");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("pk_ratings");

                    b.HasIndex("TenantId", "Reference")
                        .IsUnique()
                        .HasDatabaseName("ix_ratings_tenant_id_reference");

                    b.HasIndex("TenantId", "ShipmentReference")
                        .HasDatabaseName("ix_ratings_tenant_id_shipment_reference");

                    b.HasIndex("TenantId", "ContractId", "RateCardId")
                        .HasDatabaseName("ix_ratings_tenant_id_contract_id_rate_card_id");

                    b.HasIndex("TenantId", "Qualified", "CalculatedAt")
                        .HasDatabaseName("ix_ratings_tenant_id_qualified_calculated_at");

                    b.HasIndex("TenantId", "TransporterId", "CalculatedAt")
                        .HasDatabaseName("ix_ratings_tenant_id_transporter_id_calculated_at");

                    b.ToTable("ratings", "contracts");
                });

            modelBuilder.Entity("Tms.Modules.Contracts.Domain.RateCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<bool>("BothWays")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("both_ways");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("code");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("char(36)")
                        .HasColumnName("contract_id");

                    b.Property<string>("DestinationCity")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("destination_city");

                    b.Property<string>("DestinationKind")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("destination_kind");

                    b.Property<string>("DestinationState")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("destination_state");

                    b.Property<string>("DestinationZone")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("destination_zone");

                    b.Property<string>("DphRuleCode")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("dph_rule_code");

                    b.Property<decimal?>("MaxDistanceKm")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("max_distance_km");

                    b.Property<decimal?>("MaxVolumeCbm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("max_volume_cbm");

                    b.Property<decimal?>("MaxWeightKg")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("max_weight_kg");

                    b.Property<decimal?>("MaximumCharge")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("maximum_charge");

                    b.Property<decimal?>("MinDistanceKm")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("min_distance_km");

                    b.Property<decimal?>("MinVolumeCbm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("min_volume_cbm");

                    b.Property<decimal?>("MinWeightKg")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("min_weight_kg");

                    b.Property<decimal?>("MinimumCharge")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("minimum_charge");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("notes");

                    b.Property<string>("OriginCity")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("origin_city");

                    b.Property<string>("OriginKind")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("origin_kind");

                    b.Property<string>("OriginState")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("origin_state");

                    b.Property<string>("OriginZone")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("origin_zone");

                    b.Property<string>("Pricing")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("pricing");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100)
                        .HasColumnName("priority");

                    b.Property<string>("RequiredCapabilities")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("json")
                        .HasColumnName("required_capabilities")
                        .HasDefaultValueSql("(JSON_ARRAY())");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.Property<Guid?>("VehicleTypeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("vehicle_type_id");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_rate_cards");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_rate_cards_contract_id");

                    b.HasIndex("ContractId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_rate_cards_contract_id_code");

                    b.HasIndex("TenantId", "VehicleTypeId")
                        .HasDatabaseName("ix_rate_cards_tenant_id_vehicle_type_id");

                    b.HasIndex("TenantId", "OriginCity", "DestinationCity")
                        .HasDatabaseName("ix_rate_cards_tenant_id_origin_city_destination_city");

                    b.HasIndex("TenantId", "OriginState", "DestinationState")
                        .HasDatabaseName("ix_rate_cards_tenant_id_origin_state_destination_state");

                    b.ToTable("rate_cards", "contracts");
                });

            modelBuilder.Entity("Tms.Modules.Contracts.Domain.RateImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("applied_at");

                    b.Property<Guid?>("AppliedContractId")
                        .HasColumnType("char(36)")
                        .HasColumnName("applied_contract_id");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("char(36)")
                        .HasColumnName("contract_id");

                    b.Property<string>("ContractNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("contract_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<int>("ErrorRows")
                        .HasColumnType("int")
                        .HasColumnName("error_rows");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("mode");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("reference");

                    b.Property<int>("RowCount")
                        .HasColumnType("int")
                        .HasColumnName("row_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<int>("WarningRows")
                        .HasColumnType("int")
                        .HasColumnName("warning_rows");

                    b.HasKey("Id")
                        .HasName("pk_import_batches");

                    b.HasIndex("TenantId", "Reference")
                        .IsUnique()
                        .HasDatabaseName("ix_import_batches_tenant_id_reference");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_import_batches_tenant_id_status");

                    b.ToTable("import_batches", "contracts");
                });

            modelBuilder.Entity("Tms.Modules.Contracts.Domain.RateImportRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("char(36)")
                        .HasColumnName("batch_id");

                    b.Property<string>("Issues")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("issues");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int")
                        .HasColumnName("row_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Values")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("values");

                    b.HasKey("Id")
                        .HasName("pk_import_rows");

                    b.HasIndex("BatchId", "RowNumber")
                        .HasDatabaseName("ix_import_rows_batch_id_row_number");

                    b.ToTable("import_rows", "contracts");
                });

            modelBuilder.Entity("Tms.Modules.Contracts.Domain.RatingComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("Rate")
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)")
                        .HasColumnName("rate");

                    b.Property<Guid>("RatingId")
                        .HasColumnType("char(36)")
                        .HasColumnName("rating_id");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("reference");

                    b.Property<int>("Sequence")
                        .HasColumnType("int")
                        .HasColumnName("sequence");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("type");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_rating_components");

                    b.HasIndex("RatingId", "Sequence")
                        .HasDatabaseName("ix_rating_components_rating_id_sequence");

                    b.ToTable("rating_components", "contracts");
                });

            modelBuilder.Entity("Tms.Modules.Contracts.Domain.RatingExclusion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("ContractReference")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("contract_reference");

                    b.Property<string>("RateReference")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("rate_reference");

                    b.Property<Guid>("RatingId")
                        .HasColumnType("char(36)")
                        .HasColumnName("rating_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("reason");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("reason_code");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_rating_exclusions");

                    b.HasIndex("RatingId")
                        .HasDatabaseName("ix_rating_exclusions_rating_id");

                    b.ToTable("rating_exclusions", "contracts");
                });

            modelBuilder.Entity("Tms.Modules.Contracts.Domain.SequenceCounter", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.Property<long>("Value")
                        .HasColumnType("bigint")
                        .HasColumnName("value");

                    b.HasKey("TenantId", "Name")
                        .HasName("pk_sequences");

                    b.ToTable("sequences", "contracts");
                });

            modelBuilder.Entity("Tms.Modules.Contracts.Domain.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<string>("Members")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("members");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_zones");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_zones_tenant_id_code");

                    b.ToTable("zones", "contracts");
                });

            modelBuilder.Entity("Tms.SharedKernel.Persistence.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("action");

                    b.Property<string>("Changes")
                        .HasColumnType("json")
                        .HasColumnName("changes");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("trace_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("TenantId", "OccurredAt")
                        .HasDatabaseName("ix_audit_logs_tenant_id_occurred_at");

                    b.HasIndex("TenantId", "EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_tenant_id_entity_type_entity_id");

                    b.ToTable("audit_logs", "platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Tms.SharedKernel.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("int")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dead_lettered_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("processed_at");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAt", "DeadLetteredAt", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at_dead_lettered_at_next_attempt_at");

                    b.ToTable("outbox_messages", "platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Tms.Modules.Contracts.Domain.ContractAccessorial", b =>
                {
                    b.HasOne("Tms.Modules.Contracts.Domain.Contract", null)
                        .WithMany("Accessorials")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contract_accessorials_contracts_contract_id");
                });

            modelBuilder.Entity("Tms.Modules.Contracts.Domain.ContractCapacity", b =>
                {
                    b.HasOne("Tms.Modules.Contracts.Domain.Contract", null)
                        .WithMany("Capacities")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contract_capacity_contracts_contract_id");
                });

            modelBuilder.Entity("Tms.Modules.Contracts.Domain.ContractSla", b =>
                {
                    b.HasOne("Tms.Modules.Contracts.Domain.Contract", null)
                        .WithMany("Slas")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contract_sla_contracts_contract_id");
                });

            modelBuilder.Entity("Tms.Modules.Contracts.Domain.DphRule", b =>
                {
                    b.HasOne("Tms.Modules.Contracts.Domain.Contract", null)
                        .WithMany("DphRules")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dph_rules_contracts_contract_id");
                });

            modelBuilder.Entity("Tms.Modules.Contracts.Domain.RateCard", b =>
                {
                    b.HasOne("Tms.Modules.Contracts.Domain.Contract", null)
                        .WithMany("RateCards")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rate_cards_contracts_contract_id");
                });

            modelBuilder.Entity("Tms.Modules.Contracts.Domain.RateImportRow", b =>
                {
                    b.HasOne("Tms.Modules.Contracts.Domain.RateImportBatch", null)
                        .WithMany("Rows")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_import_rows_import_batches_batch_id");
                });

            modelBuilder.Entity("Tms.Modules.Contracts.Domain.RatingComponent", b =>
                {
                    b.HasOne("Tms.Modules.Contracts.Domain.FreightRating", null)
                        .WithMany("Components")
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rating_components_ratings_rating_id");
                });

            modelBuilder.Entity("Tms.Modules.Contracts.Domain.RatingExclusion", b =>
                {
                    b.HasOne("Tms.Modules.Contracts.Domain.FreightRating", null)
                        .WithMany("Exclusions")
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rating_exclusions_ratings_rating_id");
                });

            modelBuilder.Entity("Tms.Modules.Contracts.Domain.Contract", b =>
                {
                    b.Navigation("Accessorials");

                    b.Navigation("Capacities");

                    b.Navigation("DphRules");

                    b.Navigation("RateCards");

                    b.Navigation("Slas");
                });

            modelBuilder.Entity("Tms.Modules.Contracts.Domain.FreightRating", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("Exclusions");
                });

            modelBuilder.Entity("Tms.Modules.Contracts.Domain.RateImportBatch", b =>
                {
                    b.Navigation("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
