// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tms.Modules.Shipments.Infrastructure.Persistence;

#nullable disable

namespace Tms.Modules.Shipments.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ShipmentsDbContext))]
    [Migration("20261004133323_CollectionRunShipments")]
    partial class CollectionRunShipments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("shipments")
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Tms.Modules.Shipments.Domain.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<double>("Latitude")
                        .HasColumnType("double")
                        .HasColumnName("latitude");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("line1");

                    b.Property<double>("Longitude")
                        .HasColumnType("double")
                        .HasColumnName("longitude");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("pincode");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("type");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.HasIndex("TenantId", "City")
                        .HasDatabaseName("ix_locations_tenant_id_city");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_locations_tenant_id_code");

                    b.ToTable("locations", "shipments");
                });

            modelBuilder.Entity("Tms.Modules.Shipments.Domain.MilkRunStop", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("location_id");

                    b.Property<Guid>("MilkRunTemplateId")
                        .HasColumnType("char(36)")
                        .HasColumnName("milk_run_template_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("int")
                        .HasColumnName("sequence");

                    b.Property<int>("ServiceMinutes")
                        .HasColumnType("int")
                        .HasColumnName("service_minutes");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("type");

                    b.Property<TimeOnly?>("WindowFrom")
                        .HasColumnType("time(6)")
                        .HasColumnName("window_from");

                    b.Property<TimeOnly?>("WindowTo")
                        .HasColumnType("time(6)")
                        .HasColumnName("window_to");

                    b.HasKey("Id")
                        .HasName("pk_milk_run_stops");

                    b.HasIndex("MilkRunTemplateId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_milk_run_stops_milk_run_template_id_sequence");

                    b.HasIndex("TenantId", "LocationId")
                        .HasDatabaseName("ix_milk_run_stops_tenant_id_location_id");

                    b.ToTable("milk_run_stops", "shipments");
                });

            modelBuilder.Entity("Tms.Modules.Shipments.Domain.MilkRunTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<string>("Days")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("days");

                    b.Property<TimeOnly>("DepartureTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("departure_time");

                    b.Property<Guid>("DepotLocationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("depot_location_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<int>("MaxDurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("max_duration_minutes");

                    b.Property<int>("MaxStops")
                        .HasColumnType("int")
                        .HasColumnName("max_stops");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("VehicleTypeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("vehicle_type_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_milk_run_templates");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_milk_run_templates_tenant_id_code");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("ix_milk_run_templates_tenant_id_is_active");

                    b.ToTable("milk_run_templates", "shipments");
                });

            modelBuilder.Entity("Tms.Modules.Shipments.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("DeliverByDate")
                        .HasColumnType("date")
                        .HasColumnName("deliver_by_date");

                    b.Property<TimeOnly?>("DeliveryWindowFrom")
                        .HasColumnType("time(6)")
                        .HasColumnName("delivery_window_from");

                    b.Property<TimeOnly?>("DeliveryWindowTo")
                        .HasColumnType("time(6)")
                        .HasColumnName("delivery_window_to");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("description");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("direction");

                    b.Property<string>("Drop")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("drop");

                    b.Property<string>("DropCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("drop_city");

                    b.Property<Guid?>("DropLocationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("drop_location_id");

                    b.Property<string>("DropState")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("drop_state");

                    b.Property<int>("Handling")
                        .HasColumnType("int")
                        .HasColumnName("handling");

                    b.Property<bool>("IsHazardous")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_hazardous");

                    b.Property<bool>("IsStackable")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_stackable");

                    b.Property<decimal?>("LongestItemM")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("longest_item_m");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("number");

                    b.Property<int?>("Packages")
                        .HasColumnType("int")
                        .HasColumnName("packages");

                    b.Property<string>("Pickup")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("pickup");

                    b.Property<string>("PickupCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("pickup_city");

                    b.Property<Guid?>("PickupLocationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("pickup_location_id");

                    b.Property<string>("PickupState")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("pickup_state");

                    b.Property<TimeOnly?>("PickupWindowFrom")
                        .HasColumnType("time(6)")
                        .HasColumnName("pickup_window_from");

                    b.Property<TimeOnly?>("PickupWindowTo")
                        .HasColumnType("time(6)")
                        .HasColumnName("pickup_window_to");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<string>("ProductCategory")
                        .HasColumnType("longtext")
                        .HasColumnName("product_category");

                    b.Property<DateOnly>("ReadyDate")
                        .HasColumnType("date")
                        .HasColumnName("ready_date");

                    b.Property<string>("Reference")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("reference");

                    b.Property<string>("ReturnReason")
                        .HasColumnType("longtext")
                        .HasColumnName("return_reason");

                    b.Property<int?>("ReturnType")
                        .HasColumnType("int")
                        .HasColumnName("return_type");

                    b.Property<Guid?>("ShipmentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("shipment_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<decimal?>("VolumeCbm")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("volume_cbm");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("TenantId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_tenant_id_number");

                    b.HasIndex("TenantId", "ShipmentId")
                        .HasDatabaseName("ix_orders_tenant_id_shipment_id");

                    b.HasIndex("TenantId", "Status", "PickupState", "PickupCity")
                        .HasDatabaseName("ix_orders_tenant_id_status_pickup_state_pickup_city");

                    b.ToTable("orders", "shipments");
                });

            modelBuilder.Entity("Tms.Modules.Shipments.Domain.PlanningRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("approved_by");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTimeOffset?>("CommittedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("committed_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<string>("Log")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("log");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("number");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("options");

                    b.Property<string>("OrderIds")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("order_ids");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("plan");

                    b.Property<int>("PlanVersion")
                        .HasColumnType("int")
                        .HasColumnName("plan_version");

                    b.Property<DateOnly>("PlanningDate")
                        .HasColumnType("date")
                        .HasColumnName("planning_date");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("RunGroupId")
                        .HasColumnType("char(36)")
                        .HasColumnName("run_group_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_planning_runs");

                    b.HasIndex("TenantId", "Number", "PlanVersion")
                        .IsUnique()
                        .HasDatabaseName("ix_planning_runs_tenant_id_number_plan_version");

                    b.HasIndex("TenantId", "RunGroupId", "PlanVersion")
                        .IsUnique()
                        .HasDatabaseName("ix_planning_runs_tenant_id_run_group_id_plan_version");

                    b.HasIndex("TenantId", "Status", "PlanningDate")
                        .HasDatabaseName("ix_planning_runs_tenant_id_status_planning_date");

                    b.ToTable("planning_runs", "shipments");
                });

            modelBuilder.Entity("Tms.Modules.Shipments.Domain.PodDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<string>("FileKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("file_key");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("file_name");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("shipment_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TransporterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("transporter_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_pod_documents");

                    b.HasIndex("TenantId", "TransporterId")
                        .HasDatabaseName("ix_pod_documents_tenant_id_transporter_id");

                    b.HasIndex("TenantId", "ShipmentId", "OrderId")
                        .HasDatabaseName("ix_pod_documents_tenant_id_shipment_id_order_id");

                    b.ToTable("pod_documents", "shipments");
                });

            modelBuilder.Entity("Tms.Modules.Shipments.Domain.ProductCompatibilityRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("CategoryA")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_a");

                    b.Property<string>("CategoryB")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_b");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_compatibility_rules");

                    b.HasIndex("TenantId", "CategoryA", "CategoryB")
                        .IsUnique()
                        .HasDatabaseName("ix_compatibility_rules_tenant_id_category_a_category_b");

                    b.ToTable("compatibility_rules", "shipments");
                });

            modelBuilder.Entity("Tms.Modules.Shipments.Domain.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("accepted_at");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("cancel_reason");

                    b.Property<string>("CollectionCity")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("collection_city");

                    b.Property<string>("CollectionState")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("collection_state");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("char(36)")
                        .HasColumnName("contract_id");

                    b.Property<string>("ContractReference")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("contract_reference");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("delivered_at");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dispatched_at");

                    b.Property<decimal?>("DistanceKm")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("distance_km");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("char(36)")
                        .HasColumnName("driver_id");

                    b.Property<string>("DriverName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("driver_name");

                    b.Property<string>("DriverPhone")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("driver_phone");

                    b.Property<string>("EstimateLines")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("estimate_lines");

                    b.Property<decimal?>("FreightEstimate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("freight_estimate");

                    b.Property<string>("LastRejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("last_rejection_reason");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("mode");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("number");

                    b.Property<string>("OriginCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("origin_city");

                    b.Property<string>("OriginState")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("origin_state");

                    b.Property<string>("OverrideReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("override_reason");

                    b.Property<decimal>("PeakOnboardKg")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("peak_onboard_kg");

                    b.Property<string>("PlanReference")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("plan_reference");

                    b.Property<decimal?>("PlannedCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("planned_cost");

                    b.Property<DateOnly>("PlannedPickupDate")
                        .HasColumnType("date")
                        .HasColumnName("planned_pickup_date");

                    b.Property<int>("RejectionCount")
                        .HasColumnType("int")
                        .HasColumnName("rejection_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("TenderedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("tendered_at");

                    b.Property<decimal?>("TotalVolumeCbm")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("total_volume_cbm");

                    b.Property<decimal>("TotalWeightKg")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total_weight_kg");

                    b.Property<Guid?>("TransporterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("transporter_id");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("vehicle_id");

                    b.Property<int?>("VehiclePayloadKg")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_payload_kg");

                    b.Property<string>("VehicleRegistration")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("vehicle_registration");

                    b.Property<Guid?>("VehicleTypeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("vehicle_type_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_shipments");

                    b.HasIndex("TenantId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_shipments_tenant_id_number");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_shipments_tenant_id_status");

                    b.HasIndex("TenantId", "TransporterId", "Status")
                        .HasDatabaseName("ix_shipments_tenant_id_transporter_id_status");

                    b.ToTable("shipments", "shipments");
                });

            modelBuilder.Entity("Tms.Modules.Shipments.Domain.ShipmentOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int?>("DamagedPackages")
                        .HasColumnType("int")
                        .HasColumnName("damaged_packages");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("delivered_at");

                    b.Property<int?>("DeliveredPackages")
                        .HasColumnType("int")
                        .HasColumnName("delivered_packages");

                    b.Property<string>("DeliveryRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("delivery_remarks");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("Forward")
                        .HasColumnName("direction");

                    b.Property<int>("DropSequence")
                        .HasColumnType("int")
                        .HasColumnName("drop_sequence");

                    b.Property<bool>("IsReturn")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_return");

                    b.Property<string>("LrNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("lr_number");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)")
                        .HasColumnName("order_id");

                    b.Property<int?>("PackagesShipped")
                        .HasColumnType("int")
                        .HasColumnName("packages_shipped");

                    b.Property<string>("PodRejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("pod_rejection_reason");

                    b.Property<DateTimeOffset?>("PodReviewedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("pod_reviewed_at");

                    b.Property<Guid?>("PodReviewedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("pod_reviewed_by");

                    b.Property<string>("PodStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("Awaiting")
                        .HasColumnName("pod_status");

                    b.Property<string>("ReceiverName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("receiver_name");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("shipment_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_shipment_orders");

                    b.HasIndex("ShipmentId", "OrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_shipment_orders_shipment_id_order_id");

                    b.HasIndex("TenantId", "OrderId")
                        .HasDatabaseName("ix_shipment_orders_tenant_id_order_id");

                    b.HasIndex("TenantId", "PodStatus", "DeliveredAt")
                        .HasDatabaseName("ix_shipment_orders_tenant_id_pod_status_delivered_at");

                    b.ToTable("shipment_orders", "shipments");
                });

            modelBuilder.Entity("Tms.SharedKernel.Persistence.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("action");

                    b.Property<string>("Changes")
                        .HasColumnType("json")
                        .HasColumnName("changes");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("trace_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("TenantId", "OccurredAt")
                        .HasDatabaseName("ix_audit_logs_tenant_id_occurred_at");

                    b.HasIndex("TenantId", "EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_tenant_id_entity_type_entity_id");

                    b.ToTable("audit_logs", "platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Tms.SharedKernel.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("int")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dead_lettered_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("processed_at");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAt", "DeadLetteredAt", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at_dead_lettered_at_next_attempt_at");

                    b.ToTable("outbox_messages", "platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Tms.Modules.Shipments.Domain.MilkRunStop", b =>
                {
                    b.HasOne("Tms.Modules.Shipments.Domain.MilkRunTemplate", null)
                        .WithMany("Stops")
                        .HasForeignKey("MilkRunTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_milk_run_stops_milk_run_templates_milk_run_template_id");
                });

            modelBuilder.Entity("Tms.Modules.Shipments.Domain.ShipmentOrder", b =>
                {
                    b.HasOne("Tms.Modules.Shipments.Domain.Shipment", null)
                        .WithMany("Orders")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shipment_orders_shipments_shipment_id");
                });

            modelBuilder.Entity("Tms.Modules.Shipments.Domain.MilkRunTemplate", b =>
                {
                    b.Navigation("Stops");
                });

            modelBuilder.Entity("Tms.Modules.Shipments.Domain.Shipment", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
