// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tms.Modules.Deliveries.Infrastructure.Persistence;

#nullable disable

namespace Tms.Modules.Deliveries.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DeliveriesDbContext))]
    [Migration("20261005121852_ExceptionAttachments")]
    partial class ExceptionAttachments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pd")
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.ClaimHandoff", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("char(36)")
                        .HasColumnName("delivery_id");

                    b.Property<Guid?>("DiscrepancyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("discrepancy_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("payload_json");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("reference");

                    b.Property<string>("System")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("system");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_claim_handoffs");

                    b.HasIndex("TenantId", "DeliveryId")
                        .HasDatabaseName("ix_claim_handoffs_tenant_id_delivery_id");

                    b.HasIndex("TenantId", "Reference")
                        .IsUnique()
                        .HasDatabaseName("ix_claim_handoffs_tenant_id_reference");

                    b.ToTable("claim_handoffs", "pd");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActualArrivalAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("actual_arrival_at");

                    b.Property<DateTimeOffset?>("ActualDeliveryAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("actual_delivery_at");

                    b.Property<double?>("ArrivalAccuracy")
                        .HasColumnType("double")
                        .HasColumnName("arrival_accuracy");

                    b.Property<double?>("ArrivalLatitude")
                        .HasColumnType("double")
                        .HasColumnName("arrival_latitude");

                    b.Property<double?>("ArrivalLongitude")
                        .HasColumnType("double")
                        .HasColumnName("arrival_longitude");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("customer_email");

                    b.Property<double?>("CustomerLatitude")
                        .HasColumnType("double")
                        .HasColumnName("customer_latitude");

                    b.Property<double?>("CustomerLongitude")
                        .HasColumnType("double")
                        .HasColumnName("customer_longitude");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("customer_phone");

                    b.Property<string>("CustomerReference")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("customer_reference");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("destination_address");

                    b.Property<string>("DestinationReference")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("destination_reference");

                    b.Property<string>("DriverName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("driver_name");

                    b.Property<int?>("GeofenceRadiusM")
                        .HasColumnType("int")
                        .HasColumnName("geofence_radius_m");

                    b.Property<bool>("HasQuantityMismatch")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_quantity_mismatch");

                    b.Property<string>("LoadReference")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("load_reference");

                    b.Property<string>("LrNumber")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("lr_number");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("number");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("char(36)")
                        .HasColumnName("order_id");

                    b.Property<string>("OrderReference")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("order_reference");

                    b.Property<string>("OriginReference")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("origin_reference");

                    b.Property<int>("OtpAttempts")
                        .HasColumnType("int")
                        .HasColumnName("otp_attempts");

                    b.Property<DateTimeOffset?>("OtpExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("otp_expires_at");

                    b.Property<string>("OtpHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("otp_hash");

                    b.Property<string>("OtpSalt")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("otp_salt");

                    b.Property<DateTimeOffset?>("OtpVerifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("otp_verified_at");

                    b.Property<string>("Outcome")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("outcome");

                    b.Property<DateTimeOffset>("PlannedDeliveryAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("planned_delivery_at");

                    b.Property<string>("RemainingDisposition")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("remaining_disposition");

                    b.Property<int>("Sequence")
                        .HasColumnType("int")
                        .HasColumnName("sequence");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("service_type");

                    b.Property<Guid?>("ShipmentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("shipment_id");

                    b.Property<string>("ShipmentReference")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("shipment_reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("TransporterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("transporter_id");

                    b.Property<string>("TransporterReference")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("transporter_reference");

                    b.Property<string>("TripReference")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("trip_reference");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("vehicle_id");

                    b.Property<string>("VehicleReference")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("vehicle_reference");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<DateTimeOffset?>("WindowEnd")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("window_end");

                    b.Property<DateTimeOffset?>("WindowStart")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("window_start");

                    b.HasKey("Id")
                        .HasName("pk_deliveries");

                    b.HasIndex("TenantId", "CustomerReference")
                        .HasDatabaseName("ix_deliveries_tenant_id_customer_reference");

                    b.HasIndex("TenantId", "LoadReference")
                        .HasDatabaseName("ix_deliveries_tenant_id_load_reference");

                    b.HasIndex("TenantId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_deliveries_tenant_id_number");

                    b.HasIndex("TenantId", "PlannedDeliveryAt")
                        .HasDatabaseName("ix_deliveries_tenant_id_planned_delivery_at");

                    b.HasIndex("TenantId", "ShipmentReference")
                        .HasDatabaseName("ix_deliveries_tenant_id_shipment_reference");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_deliveries_tenant_id_status");

                    b.HasIndex("TenantId", "ShipmentId", "OrderId")
                        .HasDatabaseName("ix_deliveries_tenant_id_shipment_id_order_id");

                    b.HasIndex("TenantId", "TransporterId", "Status")
                        .HasDatabaseName("ix_deliveries_tenant_id_transporter_id_status");

                    b.ToTable("deliveries", "pd");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.DeliveryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int")
                        .HasColumnName("attempt_number");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("attempted_at");

                    b.Property<string>("CustomerRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("customer_remarks");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("char(36)")
                        .HasColumnName("delivery_id");

                    b.Property<string>("DeviceReference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("device_reference");

                    b.Property<string>("DriverRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("driver_remarks");

                    b.Property<double?>("GpsAccuracy")
                        .HasColumnType("double")
                        .HasColumnName("gps_accuracy");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double")
                        .HasColumnName("longitude");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("reason_code");

                    b.Property<string>("RecipientName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("recipient_name");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("result");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_delivery_attempts");

                    b.HasIndex("DeliveryId")
                        .HasDatabaseName("ix_delivery_attempts_delivery_id");

                    b.HasIndex("TenantId", "DeliveryId", "AttemptNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_delivery_attempts_tenant_id_delivery_id_attempt_number");

                    b.ToTable("delivery_attempts", "pd");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.DeliveryDiscrepancy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("ClaimReference")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("claim_reference");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("CustomerAcknowledged")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("customer_acknowledged");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("char(36)")
                        .HasColumnName("delivery_id");

                    b.Property<Guid>("DeliveryItemId")
                        .HasColumnType("char(36)")
                        .HasColumnName("delivery_item_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("quantity");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("reason_code");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_delivery_discrepancies");

                    b.HasIndex("DeliveryId")
                        .HasDatabaseName("ix_delivery_discrepancies_delivery_id");

                    b.HasIndex("TenantId", "DeliveryId")
                        .HasDatabaseName("ix_delivery_discrepancies_tenant_id_delivery_id");

                    b.HasIndex("TenantId", "Type", "CreatedAt")
                        .HasDatabaseName("ix_delivery_discrepancies_tenant_id_type_created_at");

                    b.ToTable("delivery_discrepancies", "pd");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.DeliveryEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("char(36)")
                        .HasColumnName("delivery_id");

                    b.Property<string>("DeviceReference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("device_reference");

                    b.Property<DateTimeOffset>("EventAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("event_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("event_type");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double")
                        .HasColumnName("longitude");

                    b.Property<Guid?>("PerformedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("performed_by");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("remarks");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_delivery_events");

                    b.HasIndex("DeliveryId")
                        .HasDatabaseName("ix_delivery_events_delivery_id");

                    b.HasIndex("TenantId", "DeliveryId", "EventAt")
                        .HasDatabaseName("ix_delivery_events_tenant_id_delivery_id_event_at");

                    b.ToTable("delivery_events", "pd");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.DeliveryException", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("ActionTaken")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("action_taken");

                    b.Property<string>("ClaimReference")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("claim_reference");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("char(36)")
                        .HasColumnName("delivery_id");

                    b.Property<string>("DeliveryNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("delivery_number");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("department");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("due_at");

                    b.Property<DateTimeOffset?>("EscalatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("escalated_at");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("exception_type");

                    b.Property<decimal?>("FinancialImpact")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("financial_impact");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("number");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("owner_user_id");

                    b.Property<Guid?>("PodId")
                        .HasColumnType("char(36)")
                        .HasColumnName("pod_id");

                    b.Property<DateTimeOffset>("RaisedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("raised_at");

                    b.Property<string>("Resolution")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("resolution");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResponsibleParty")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("responsible_party");

                    b.Property<string>("RootCause")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("root_cause");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("TransporterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("transporter_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_delivery_exceptions");

                    b.HasIndex("TenantId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_delivery_exceptions_tenant_id_number");

                    b.HasIndex("TenantId", "DeliveryId", "ExceptionType")
                        .HasDatabaseName("ix_delivery_exceptions_tenant_id_delivery_id_exception_type");

                    b.HasIndex("TenantId", "TransporterId", "Status")
                        .HasDatabaseName("ix_delivery_exceptions_tenant_id_transporter_id_status");

                    b.HasIndex("TenantId", "Status", "Severity", "DueAt")
                        .HasDatabaseName("ix_delivery_exceptions_tenant_id_status_severity_due_at");

                    b.ToTable("delivery_exceptions", "pd");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.DeliveryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("DamageDescription")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("damage_description");

                    b.Property<string>("DamageReason")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("damage_reason");

                    b.Property<string>("DamageType")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("damage_type");

                    b.Property<decimal>("DamagedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("damaged_quantity");

                    b.Property<decimal?>("DeliveredQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("delivered_quantity");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("char(36)")
                        .HasColumnName("delivery_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("description");

                    b.Property<decimal>("DispatchedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("dispatched_quantity");

                    b.Property<decimal>("OrderedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("ordered_quantity");

                    b.Property<decimal>("RejectedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("rejected_quantity");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("remarks");

                    b.Property<decimal>("ShortQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("short_quantity");

                    b.Property<string>("ShortageReasonCode")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("shortage_reason_code");

                    b.Property<string>("SkuReference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("sku_reference");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("unit_of_measure");

                    b.HasKey("Id")
                        .HasName("pk_delivery_items");

                    b.HasIndex("DeliveryId")
                        .HasDatabaseName("ix_delivery_items_delivery_id");

                    b.HasIndex("TenantId", "DeliveryId")
                        .HasDatabaseName("ix_delivery_items_tenant_id_delivery_id");

                    b.HasIndex("TenantId", "SkuReference")
                        .HasDatabaseName("ix_delivery_items_tenant_id_sku_reference");

                    b.ToTable("delivery_items", "pd");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.DeliveryNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AudiencePermission")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("audience_permission");

                    b.Property<Guid?>("AudienceTransporterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("audience_transporter_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("dedupe_key");

                    b.Property<Guid?>("DeliveryId")
                        .HasColumnType("char(36)")
                        .HasColumnName("delivery_id");

                    b.Property<Guid?>("ExceptionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("exception_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("kind");

                    b.Property<Guid?>("PodId")
                        .HasColumnType("char(36)")
                        .HasColumnName("pod_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("TenantId", "DedupeKey")
                        .IsUnique()
                        .HasDatabaseName("ix_notifications_tenant_id_dedupe_key");

                    b.HasIndex("TenantId", "AudiencePermission", "CreatedAt")
                        .HasDatabaseName("ix_notifications_tenant_id_audience_permission_created_at");

                    b.HasIndex("TenantId", "AudienceTransporterId", "CreatedAt")
                        .HasDatabaseName("ix_notifications_tenant_id_audience_transporter_id_created_at");

                    b.ToTable("notifications", "pd");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.DeliverySetting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("value_json");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_settings");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_settings_tenant_id_key");

                    b.ToTable("settings", "pd");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.ExceptionAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("at");

                    b.Property<Guid?>("By")
                        .HasColumnType("char(36)")
                        .HasColumnName("by");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("content_type");

                    b.Property<Guid>("ExceptionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("exception_id");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("file_hash");

                    b.Property<string>("FileKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("file_key");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("note");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_exception_attachments");

                    b.HasIndex("ExceptionId")
                        .HasDatabaseName("ix_exception_attachments_exception_id");

                    b.HasIndex("TenantId", "ExceptionId", "At")
                        .HasDatabaseName("ix_exception_attachments_tenant_id_exception_id_at");

                    b.ToTable("exception_attachments", "pd");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.ExceptionNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("at");

                    b.Property<Guid?>("By")
                        .HasColumnType("char(36)")
                        .HasColumnName("by");

                    b.Property<Guid>("ExceptionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("exception_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_exception_notes");

                    b.HasIndex("ExceptionId")
                        .HasDatabaseName("ix_exception_notes_exception_id");

                    b.HasIndex("TenantId", "ExceptionId", "At")
                        .HasDatabaseName("ix_exception_notes_tenant_id_exception_id_at");

                    b.ToTable("exception_notes", "pd");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.IntegrationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("char(36)")
                        .HasColumnName("delivery_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("kind");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("payload_json");

                    b.Property<Guid?>("PodId")
                        .HasColumnType("char(36)")
                        .HasColumnName("pod_id");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("target");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_integration_messages");

                    b.HasIndex("TenantId", "DeliveryId", "CreatedAt")
                        .HasDatabaseName("ix_integration_messages_tenant_id_delivery_id_created_at");

                    b.HasIndex("TenantId", "Target", "CreatedAt")
                        .HasDatabaseName("ix_integration_messages_tenant_id_target_created_at");

                    b.ToTable("integration_messages", "pd");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.NotificationRead", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("notification_id");

                    b.Property<DateTimeOffset>("ReadAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("read_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notification_reads");

                    b.HasIndex("TenantId", "UserId")
                        .HasDatabaseName("ix_notification_reads_tenant_id_user_id");

                    b.HasIndex("TenantId", "NotificationId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_reads_tenant_id_notification_id_user_id");

                    b.ToTable("notification_reads", "pd");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.PodEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("captured_at");

                    b.Property<Guid?>("CapturedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("captured_by");

                    b.Property<string>("ClientRecordId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("client_record_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("content_type");

                    b.Property<string>("DeviceReference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("device_reference");

                    b.Property<string>("EvidenceType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("evidence_type");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("file_hash");

                    b.Property<string>("FileKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("file_key");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("file_name");

                    b.Property<int?>("Height")
                        .HasColumnType("int")
                        .HasColumnName("height");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double")
                        .HasColumnName("longitude");

                    b.Property<Guid>("PodId")
                        .HasColumnType("char(36)")
                        .HasColumnName("pod_id");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("removed_at");

                    b.Property<string>("RemovedReason")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("removed_reason");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Warnings")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("warnings");

                    b.Property<int?>("Width")
                        .HasColumnType("int")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_pod_evidence");

                    b.HasIndex("PodId")
                        .HasDatabaseName("ix_pod_evidence_pod_id");

                    b.HasIndex("TenantId", "FileHash")
                        .HasDatabaseName("ix_pod_evidence_tenant_id_file_hash");

                    b.HasIndex("TenantId", "PodId")
                        .HasDatabaseName("ix_pod_evidence_tenant_id_pod_id");

                    b.HasIndex("TenantId", "PodId", "ClientRecordId")
                        .IsUnique()
                        .HasDatabaseName("ix_pod_evidence_tenant_id_pod_id_client_record_id");

                    b.ToTable("pod_evidence", "pd");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.PodItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<decimal>("DamagedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("damaged_quantity");

                    b.Property<decimal>("DeliveredQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("delivered_quantity");

                    b.Property<Guid>("DeliveryItemId")
                        .HasColumnType("char(36)")
                        .HasColumnName("delivery_item_id");

                    b.Property<decimal>("DispatchedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("dispatched_quantity");

                    b.Property<decimal>("OrderedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("ordered_quantity");

                    b.Property<Guid>("PodId")
                        .HasColumnType("char(36)")
                        .HasColumnName("pod_id");

                    b.Property<decimal>("RejectedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("rejected_quantity");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("remarks");

                    b.Property<decimal>("ShortQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("short_quantity");

                    b.Property<string>("SkuReference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("sku_reference");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_pod_items");

                    b.HasIndex("PodId")
                        .HasDatabaseName("ix_pod_items_pod_id");

                    b.HasIndex("TenantId", "PodId")
                        .HasDatabaseName("ix_pod_items_tenant_id_pod_id");

                    b.ToTable("pod_items", "pd");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.PodOcrField", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("BoundingBoxJson")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("bounding_box_json");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("confidence");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("field_name");

                    b.Property<string>("NormalizedValue")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("normalized_value");

                    b.Property<Guid>("OcrResultId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ocr_result_id");

                    b.Property<string>("RawValue")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("raw_value");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("ReviewedValue")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("reviewed_value");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ValidationMessage")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("validation_message");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("validation_status");

                    b.HasKey("Id")
                        .HasName("pk_pod_ocr_fields");

                    b.HasIndex("OcrResultId")
                        .HasDatabaseName("ix_pod_ocr_fields_ocr_result_id");

                    b.HasIndex("TenantId", "ValidationStatus")
                        .HasDatabaseName("ix_pod_ocr_fields_tenant_id_validation_status");

                    b.HasIndex("TenantId", "OcrResultId", "FieldName")
                        .HasDatabaseName("ix_pod_ocr_fields_tenant_id_ocr_result_id_field_name");

                    b.ToTable("pod_ocr_fields", "pd");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.PodOcrResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("document_type");

                    b.Property<string>("Error")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("error");

                    b.Property<Guid>("EvidenceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("evidence_id");

                    b.Property<decimal?>("OverallConfidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("overall_confidence");

                    b.Property<Guid>("PodId")
                        .HasColumnType("char(36)")
                        .HasColumnName("pod_id");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("processed_at");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("processing_status");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset>("QueuedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("queued_at");

                    b.Property<string>("RawResponseReference")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("raw_response_reference");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_pod_ocr_results");

                    b.HasIndex("PodId")
                        .HasDatabaseName("ix_pod_ocr_results_pod_id");

                    b.HasIndex("TenantId", "PodId")
                        .HasDatabaseName("ix_pod_ocr_results_tenant_id_pod_id");

                    b.HasIndex("TenantId", "ProcessingStatus")
                        .HasDatabaseName("ix_pod_ocr_results_tenant_id_processing_status");

                    b.ToTable("pod_ocr_results", "pd");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.PodRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("approved_at");

                    b.Property<DateTimeOffset?>("ArrivalAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("arrival_at");

                    b.Property<bool>("AutoAccepted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("auto_accepted");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("captured_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<bool>("CustomerAcknowledged")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("customer_acknowledged");

                    b.Property<DateTimeOffset?>("DeliveryCompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("delivery_completed_at");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("char(36)")
                        .HasColumnName("delivery_id");

                    b.Property<bool>("DriverConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("driver_confirmed");

                    b.Property<string>("DriverRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("driver_remarks");

                    b.Property<DateTimeOffset?>("FirstSubmittedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("first_submitted_at");

                    b.Property<string>("Geofence")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("geofence");

                    b.Property<double?>("GpsAccuracy")
                        .HasColumnType("double")
                        .HasColumnName("gps_accuracy");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_current");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double")
                        .HasColumnName("longitude");

                    b.Property<string>("Method")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("method");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("modified_by");

                    b.Property<int>("OtpAttempts")
                        .HasColumnType("int")
                        .HasColumnName("otp_attempts");

                    b.Property<bool>("OtpVerified")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("otp_verified");

                    b.Property<DateTimeOffset?>("OtpVerifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("otp_verified_at");

                    b.Property<string>("PodNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("pod_number");

                    b.Property<int>("PodVersion")
                        .HasColumnType("int")
                        .HasColumnName("pod_version");

                    b.Property<string>("RecipientDesignation")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("recipient_designation");

                    b.Property<string>("RecipientName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("recipient_name");

                    b.Property<string>("RecipientPhone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("recipient_phone");

                    b.Property<string>("RecipientRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("recipient_remarks");

                    b.Property<int>("RejectionCount")
                        .HasColumnType("int")
                        .HasColumnName("rejection_count");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTimeOffset?>("ResubmittedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("resubmitted_at");

                    b.Property<DateTimeOffset?>("ReturnedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("returned_at");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("submitted_at");

                    b.Property<Guid?>("SupersedesPodId")
                        .HasColumnType("char(36)")
                        .HasColumnName("supersedes_pod_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_pod_records");

                    b.HasIndex("TenantId", "ApprovedAt")
                        .HasDatabaseName("ix_pod_records_tenant_id_approved_at");

                    b.HasIndex("TenantId", "ReturnedAt")
                        .HasDatabaseName("ix_pod_records_tenant_id_returned_at");

                    b.HasIndex("TenantId", "DeliveryId", "IsCurrent")
                        .HasDatabaseName("ix_pod_records_tenant_id_delivery_id_is_current");

                    b.HasIndex("TenantId", "PodNumber", "PodVersion")
                        .IsUnique()
                        .HasDatabaseName("ix_pod_records_tenant_id_pod_number_pod_version");

                    b.HasIndex("TenantId", "Status", "SubmittedAt")
                        .HasDatabaseName("ix_pod_records_tenant_id_status_submitted_at");

                    b.ToTable("pod_records", "pd");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.PodReviewAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("action");

                    b.Property<string>("FieldName")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("field_name");

                    b.Property<string>("NewValue")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("old_value");

                    b.Property<DateTimeOffset>("PerformedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("performed_at");

                    b.Property<Guid?>("PerformedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("performed_by");

                    b.Property<Guid>("PodId")
                        .HasColumnType("char(36)")
                        .HasColumnName("pod_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_pod_review_actions");

                    b.HasIndex("PodId")
                        .HasDatabaseName("ix_pod_review_actions_pod_id");

                    b.HasIndex("TenantId", "PodId", "PerformedAt")
                        .HasDatabaseName("ix_pod_review_actions_tenant_id_pod_id_performed_at");

                    b.ToTable("pod_review_actions", "pd");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.PodSignature", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("captured_at");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("file_hash");

                    b.Property<string>("FileKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("file_key");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double")
                        .HasColumnName("longitude");

                    b.Property<Guid>("PodId")
                        .HasColumnType("char(36)")
                        .HasColumnName("pod_id");

                    b.Property<string>("SignerDesignation")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("signer_designation");

                    b.Property<string>("SignerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("signer_name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("VerificationMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("verification_method");

                    b.HasKey("Id")
                        .HasName("pk_pod_signatures");

                    b.HasIndex("PodId")
                        .HasDatabaseName("ix_pod_signatures_pod_id");

                    b.HasIndex("TenantId", "PodId")
                        .HasDatabaseName("ix_pod_signatures_tenant_id_pod_id");

                    b.ToTable("pod_signatures", "pd");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.PodValidationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Check")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("check");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("message");

                    b.Property<Guid>("PodId")
                        .HasColumnType("char(36)")
                        .HasColumnName("pod_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("ValidatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("validated_at");

                    b.Property<string>("ValidationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("validation_type");

                    b.HasKey("Id")
                        .HasName("pk_pod_validation_results");

                    b.HasIndex("PodId")
                        .HasDatabaseName("ix_pod_validation_results_pod_id");

                    b.HasIndex("TenantId", "PodId")
                        .HasDatabaseName("ix_pod_validation_results_tenant_id_pod_id");

                    b.ToTable("pod_validation_results", "pd");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.SyncRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClientCreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("client_created_at");

                    b.Property<string>("ClientRecordId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("client_record_id");

                    b.Property<DateTimeOffset?>("ClientUpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("client_updated_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("DeliveryId")
                        .HasColumnType("char(36)")
                        .HasColumnName("delivery_id");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("LastAttemptAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_attempt_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("operation");

                    b.Property<string>("ResultJson")
                        .HasColumnType("longtext")
                        .HasColumnName("result_json");

                    b.Property<Guid?>("ServerRecordId")
                        .HasColumnType("char(36)")
                        .HasColumnName("server_record_id");

                    b.Property<int>("SyncAttempt")
                        .HasColumnType("int")
                        .HasColumnName("sync_attempt");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("sync_status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_pod_sync_records");

                    b.HasIndex("TenantId", "ClientRecordId")
                        .IsUnique()
                        .HasDatabaseName("ix_pod_sync_records_tenant_id_client_record_id");

                    b.HasIndex("TenantId", "SyncStatus")
                        .HasDatabaseName("ix_pod_sync_records_tenant_id_sync_status");

                    b.ToTable("pod_sync_records", "pd");
                });

            modelBuilder.Entity("Tms.SharedKernel.Persistence.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("action");

                    b.Property<string>("Changes")
                        .HasColumnType("json")
                        .HasColumnName("changes");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("trace_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("TenantId", "OccurredAt")
                        .HasDatabaseName("ix_audit_logs_tenant_id_occurred_at");

                    b.HasIndex("TenantId", "EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_tenant_id_entity_type_entity_id");

                    b.ToTable("audit_logs", "platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Tms.SharedKernel.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("int")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dead_lettered_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("processed_at");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAt", "DeadLetteredAt", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at_dead_lettered_at_next_attempt_at");

                    b.ToTable("outbox_messages", "platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.DeliveryAttempt", b =>
                {
                    b.HasOne("Tms.Modules.Deliveries.Domain.Delivery", null)
                        .WithMany("Attempts")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_attempts_deliveries_delivery_id");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.DeliveryDiscrepancy", b =>
                {
                    b.HasOne("Tms.Modules.Deliveries.Domain.Delivery", null)
                        .WithMany("Discrepancies")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_discrepancies_deliveries_delivery_id");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.DeliveryEvent", b =>
                {
                    b.HasOne("Tms.Modules.Deliveries.Domain.Delivery", null)
                        .WithMany("Events")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_events_deliveries_delivery_id");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.DeliveryItem", b =>
                {
                    b.HasOne("Tms.Modules.Deliveries.Domain.Delivery", null)
                        .WithMany("Items")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_items_deliveries_delivery_id");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.ExceptionAttachment", b =>
                {
                    b.HasOne("Tms.Modules.Deliveries.Domain.DeliveryException", null)
                        .WithMany("Attachments")
                        .HasForeignKey("ExceptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exception_attachments_delivery_exceptions_exception_id");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.ExceptionNote", b =>
                {
                    b.HasOne("Tms.Modules.Deliveries.Domain.DeliveryException", null)
                        .WithMany("Notes")
                        .HasForeignKey("ExceptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exception_notes_delivery_exceptions_exception_id");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.PodEvidence", b =>
                {
                    b.HasOne("Tms.Modules.Deliveries.Domain.PodRecord", null)
                        .WithMany("Evidence")
                        .HasForeignKey("PodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pod_evidence_pod_records_pod_id");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.PodItem", b =>
                {
                    b.HasOne("Tms.Modules.Deliveries.Domain.PodRecord", null)
                        .WithMany("Items")
                        .HasForeignKey("PodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pod_items_pod_records_pod_id");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.PodOcrField", b =>
                {
                    b.HasOne("Tms.Modules.Deliveries.Domain.PodOcrResult", null)
                        .WithMany("Fields")
                        .HasForeignKey("OcrResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pod_ocr_fields_pod_ocr_results_ocr_result_id");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.PodOcrResult", b =>
                {
                    b.HasOne("Tms.Modules.Deliveries.Domain.PodRecord", null)
                        .WithMany("OcrResults")
                        .HasForeignKey("PodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pod_ocr_results_pod_records_pod_id");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.PodReviewAction", b =>
                {
                    b.HasOne("Tms.Modules.Deliveries.Domain.PodRecord", null)
                        .WithMany("Reviews")
                        .HasForeignKey("PodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pod_review_actions_pod_records_pod_id");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.PodSignature", b =>
                {
                    b.HasOne("Tms.Modules.Deliveries.Domain.PodRecord", null)
                        .WithMany("Signatures")
                        .HasForeignKey("PodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pod_signatures_pod_records_pod_id");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.PodValidationResult", b =>
                {
                    b.HasOne("Tms.Modules.Deliveries.Domain.PodRecord", null)
                        .WithMany("Validations")
                        .HasForeignKey("PodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pod_validation_results_pod_records_pod_id");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.Delivery", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Discrepancies");

                    b.Navigation("Events");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.DeliveryException", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.PodOcrResult", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Tms.Modules.Deliveries.Domain.PodRecord", b =>
                {
                    b.Navigation("Evidence");

                    b.Navigation("Items");

                    b.Navigation("OcrResults");

                    b.Navigation("Reviews");

                    b.Navigation("Signatures");

                    b.Navigation("Validations");
                });
#pragma warning restore 612, 618
        }
    }
}
