namespace Tms.SharedKernel.Contracts;

/// <summary>
/// Opaque blob storage for uploaded documents (compliance papers, PODs, contracts). Keys are generated by the
/// application, never taken from user input. Swap the implementation for cloud storage without touching callers.
/// </summary>
public interface IFileStore
{
    Task SaveAsync(string key, Stream content, CancellationToken cancellationToken = default);

    /// <summary>Returns null when the key does not exist. The caller disposes the stream.</summary>
    Task<Stream?> OpenReadAsync(string key, CancellationToken cancellationToken = default);

    Task DeleteAsync(string key, CancellationToken cancellationToken = default);
}
